version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    restart: always
    ports:
      - "16545:16545"
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres

  nginx:
    image: pagespeed/nginx-pagespeed:stable
    restart: always
    env_file:
      - .env
    entrypoint: ["/nginx-entrypoint.sh"]
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./sh/nginx-entrypoint.sh:/nginx-entrypoint.sh
      - ./data/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
      - ../data/nginx/cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - postgres

